name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # - cudatoolkit=11.8
  - plyfile
  - python=3.9
  - pip=24.2
  - pytorch
  - torchaudio
  - torchvision
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib
